### ISSUE TITLE
Add Matrix Multiplication

### ISSUE THREAD

**Issue by thekrasich** [thekrasich/SMatrix#4]

**Comment by vasenavka** [comment]
`public void MatrixMultiplication(Matrix obj)
        {
            double[,] mult = new double[elements.GetLength(0), obj.elements.GetLength(1)];

            if (elements.GetLength(0) != obj.elements.GetLength(1))
            {
                throw new InvalidOperationException("Cannot multiply two matrixes.");
            }
            else
            {
                for (int i = 0; i < elements.GetLength(0); i++)
                {
                    for (int j = 0; j < obj.elements.GetLength(1); j++)
                    {
                        mult[i, j] = 0;
                        for (int k = 0; k < elements.GetLength(0); k++)
                        {
                            mult[i, j] += this.elements[i, k] * obj.elements[k, j];
                        }
                    }
                }

                //output
                /*for (int i = 0; i < mult.GetLength(0); i++, Console.WriteLine("\n"))
                {
                    for (int j = 0; j < mult.GetLength(1); j++, Console.Write("\t"))
                    {
                        Console.Write(elements[i, j]);
                    }
                }*/
            }
        }`
